version: "3"

services:
    router:
        build:
            context: .
            dockerfile: Dockerfile-ubuntu
        ports:
            - 5672:5672
        links:
            - rabbitmq-1
            - rabbitmq-2
        volumes:
            - ./router:/custom-config

    rabbitmq-1:
        build:
            context: .
            dockerfile: Dockerfile-rabbitmq
        ports:
            - 15672:15672

    rabbitmq-2:
        build:
            context: .
            dockerfile: Dockerfile-rabbitmq
        ports:
            - 25672:15672
