version: "3"

services:
    router:
        build:
            context: .
            dockerfile: Dockerfile-ubuntu
        ports:
            - 5672:5672
        links:
            # - rabbitmq-1
            # - rabbitmq-2
            - artemis-1
            - artemis-2
        volumes:
            - ./router:/custom-config

    artemis-1:
        image: vromero/activemq-artemis:2.3.0
        ports:
          - 18161:8161
          # - 5672:5672
        environment:
          ARTEMIS_USERNAME: admin
          ARTEMIS_PASSWORD: admin

    artemis-2:
        image: vromero/activemq-artemis:2.3.0
        ports:
          - 28161:8161
        environment:
          ARTEMIS_USERNAME: admin
          ARTEMIS_PASSWORD: admin

#    rabbitmq-1:
#        build:
#            context: .
#            dockerfile: Dockerfile-rabbitmq
#        ports:
#            - 15672:15672
#
#    rabbitmq-2:
#        build:
#            context: .
#            dockerfile: Dockerfile-rabbitmq
#        ports:
#            - 25672:15672
